name: Coverage

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc13"
            compiler: "gcc-13"
            build: coverage
            build_type: Debug

    steps:
      # How many commits do we need to fetch to also fetch the branch point?
      - name: Get fetch depth
        id: fetch_depth
        run: echo "depth=$(( ${{ github.event.pull_request.commits }} + 2 ))" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ steps.fetch_depth.outputs.depth }}
          submodules: true

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 525M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.16.9

      - name: Install gcovr
        run: |
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/${CC/gcc/gcov} 100
          pip install gcovr==5.2

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                            -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                                            -DHIBF_NATIVE_BUILD=OFF \
                                            -DHIBF_VERBOSE_TESTS=OFF \
                                            -DHIBF_COVERAGE_PARALLEL_LEVEL=2
          make -j2 gtest_build

      - name: Build tests
        env:
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
          GCOV: ${{ github.workspace }}/.github/workflows/scripts/gcov.sh
        run: |
          ccache -z
          cd build
          make -k -j2
          ccache -sv

      - name: Submit coverage build
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/build/coverage.xml
          fail_ci_if_error: false
