# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: IWYU

on:
  schedule:
    - cron: "0 4 * * MON"
  workflow_dispatch:

concurrency:
  group: iwyu-actions
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: IWYU
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    container:
      image: ghcr.io/seqan/clang-19
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Run IWYU
        uses: eseiler/actions/iwyu@feature/iwyu
        with:
          configure_path: test/all
          token: ${{ github.token }}
