# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: misc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Snippet clang17"
            compiler: "clang-17"
            build: snippet
            build_type: Release
            use_include_dependencies: "OFF"
            cxx_flags: "-stdlib=libc++"

          - name: "Snippet gcc11"
            compiler: "gcc-11"
            build: snippet
            build_type: Release
            use_include_dependencies: "OFF"

          - name: "Performance clang17"
            compiler: "clang-17"
            build: performance
            build_type: Release
            use_include_dependencies: "OFF"
            cxx_flags: "-stdlib=libc++"

          - name: "Performance gcc11"
            compiler: "gcc-11"
            build: performance
            build_type: Release
            use_include_dependencies: "OFF"

          - name: "Header clang17"
            compiler: "clang-17"
            build: header
            build_type: Release
            use_include_dependencies: "OFF"
            cxx_flags: "-stdlib=libc++"

          - name: "Header gcc13"
            compiler: "gcc-13"
            build: header
            build_type: Release
            use_include_dependencies: "OFF"

          - name: "Header gcc11"
            compiler: "gcc-11"
            build: header
            build_type: Release
            use_include_dependencies: "OFF"

          - name: "Non-cyclic tests"
            compiler: "gcc-12"
            build: unit
            build_type: Debug
            use_include_dependencies: "ON"

          - name: "Tutorial"
            compiler: "gcc-11"
            build: tutorial
            build_type: Debug
            use_include_dependencies: "OFF"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 75M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: ${{ contains(matrix.build, 'tutorial') && '3.21.7' || '3.18.6' }}

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                            -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                                            -DHIBF_VERBOSE_TESTS=OFF \
                                            -DHIBF_USE_INCLUDE_DEPENDENCIES="${{ matrix.use_include_dependencies }}"
          case "${{ matrix.build }}" in
            unit) make -j2 gtest_main;;
            snippet) make -j2 gtest_main;;
            performance) make -j2 benchmark_main;;
            header) make -j2 gtest_main benchmark_main;;
          esac

      - name: Check cyclic includes
        if: matrix.use_include_dependencies == 'ON'
        run: |
          cd build
          make -k -j2 all_dependencies
          cmake .

      - name: Build tests
        if: matrix.use_include_dependencies == 'OFF'
        run: |
          ccache -z
          cd build
          make -k -j2
          ccache -sv

      - name: Run tests
        if: matrix.use_include_dependencies == 'OFF'
        run: |
          cd build
          ctest . -j2 --output-on-failure
