name: Lint

on:
  pull_request_target:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  # Cancel other workflows that are dependent on this workflow by adding jobs that have the same concurrency group.
  cancel_linux:
    name: Cancel Linux
    concurrency:
      group: linux-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Linux"
        run: echo "Cancelling Linux"
  cancel_macos:
    name: Cancel macOS
    concurrency:
      group: macos-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel macOS"
        run: echo "Cancelling macOS"
  cancel_misc:
    name: Cancel Misc
    concurrency:
      group: misc-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Misc"
        run: echo "Cancelling Misc"
  cancel_coverage:
    name: Cancel Coverage
    concurrency:
      group: coverage-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    steps:
      - name: "Cancel Coverage"
        run: echo "Cancelling Coverage"
  lint:
    name: clang-format
    concurrency:
      group: clang-format-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    needs: [cancel_linux, cancel_macos, cancel_misc, cancel_coverage]
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Add label
        env:
            GITHUB_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
            PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr edit $PR_URL --add-label "clang-format"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: false

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.cpp
            *.hpp

      - name: Copy upstream .clang-format
        run: |
          git remote add upstream ${{ github.event.pull_request.base.repo.html_url }}
          git show upstream/${{ github.event.pull_request.base.ref }}:.clang-format | \
          tee ${{ github.workspace }}/.clang-format

      - name: Run clang-format
        if: ${{ steps.changed_files.outputs.any_changed == 'true' }}
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: ${{ steps.changed_files.outputs.all_changed_files }}
          clangFormatVersion: 15
          inplace: True

      - name: Import GPG key
        if: ${{ steps.changed_files.outputs.any_changed == 'true' }}
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes
        if: ${{ steps.changed_files.outputs.any_changed == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: seqan-actions[bot]
          author_email: seqan-actions@users.noreply.github.com
          message: '[MISC] clang-format'

      # Wait for 5 seconds such that workflows triggered by adding the label run on the newest commit.
      - name: Defer workflow
        if: ${{ steps.changed_files.outputs.any_changed == 'true' }}
        run: sleep 5

      - name: Remove label
        env:
            GITHUB_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
            PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr edit $PR_URL --remove-label "clang-format"
