name: Cookbook

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: cookbook-update-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  cookbook-update:
    name: Update
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update Cookbook
        run: ./test/scripts/add_snippets_to_cookbook.sh .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ./doc/cookbook/index.md
          author_name: seqan-actions[bot]
          author_email: seqan-actions@users.noreply.github.com
          message: '[MISC] Update Cookbook'
